# WhoAmI
#
# Copyright Â© 2017-2020 Jeron Aldaron Lau.
# Dual-licensed under either the MIT License or the Boost Software License,
# Version 1.0. (See accompanying file LICENSE_BSL.txt or copy at
# https://www.boost.org/LICENSE_1_0.txt, and accompanying file LICENSE_MIT.txt
# or copy at https://opensource.org/licenses/MIT)

[package]
name = "whoami"
version = "0.9.0"
authors = [
    "Jeron Aldaron Lau <jeronlau@plopgrizzly.com>",
]
edition = "2018"
license = "MIT OR BSL-1.0"
documentation = "https://docs.rs/whoami"
homepage = "https://libcala.github.io/whoami"
repository = "https://github.com/libcala/whoami"
readme = "README.md"
description = "Retrieve the current user and environment."
keywords = ["user", "username", "whoami", "platform", "detect"]
categories = ["os"]

# Use cala_core to support all of: wasm-pack, cargo-cala-web and cargo-web
[target.'cfg(target_arch = "wasm32")'.dependencies.cala_core]
version = "0.1"
optional = true

[features]
default = []
cala = ["cala_core/cala"]
stdweb = ["cala_core/stdweb"]
wasm-bindgen = ["cala_core/wasm-bindgen"]
